name: "PHPStan"
description: "Run PHPStan against a PrestaShop version"

inputs:
  php-version:
    description: "PHP version to use"
    required: false
    default: "8.1"
  presta-version:
    description: "PrestaShop version to test against"
    required: false
    default: "latest"
  module-name:
    description: "The module name (folder under PrestaShop modules/)"
    required: true
  phpstan-config:
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    - uses: actions/checkout@v4

    - name: Cache vendor folder
      uses: actions/cache@v4
      with:
        path: vendor
        key: php-${{ hashFiles('composer.lock') }}

    - name: Cache composer folder
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: php-composer-cache

    - run: composer install
      shell: bash

    - name: Execute PHPStan
      run: $GITHUB_ACTION_PATH/scripts/phpstan.sh \
             ${{ inputs.presta-version }} \
             ${{ inputs.php-version }} \
             ${{ inputs.module-name }} \
             ${{ inputs.phpstan-config }}
      shell: bash
